import { GITHUB_TOKEN, GITHUB_REPO, GITHUB_BRANCH } from "./admin-config.js";

const API_URL = "https://api.github.com";

export const githubModule = {
  // Load catalog from static file (generated by workflow)
  async loadCatalogFromGitHub() {
    try {
      const url = `${API_URL}/repos/${GITHUB_REPO}/contents/public/catalog-data.json?ref=${GITHUB_BRANCH}`;
      const response = await fetch(url, {
        headers: {
          Accept: "application/vnd.github.v3.raw"
        }
      });

      if (!response.ok) {
        console.warn(`Could not load catalog from GitHub: ${response.status}`);
        return null;
      }

      const text = await response.text();
      return JSON.parse(text);
    } catch (err) {
      console.error("Failed to load catalog from GitHub:", err);
      return null;
    }
  },

  // Trigger GitHub Action workflow to update catalog
  async saveCatalogToGitHub(data) {
    try {
      const url = `${API_URL}/repos/${GITHUB_REPO}/actions/workflows/update-catalog.yml/dispatches`;
      
      const payload = {
        ref: GITHUB_BRANCH,
        inputs: {
          catalog_data: JSON.stringify(data, null, 2)
        }
      };

      const response = await fetch(url, {
        method: "POST",
        headers: {
          Authorization: `token ${GITHUB_TOKEN}`,
          Accept: "application/vnd.github.v3+json",
          "Content-Type": "application/json"
        },
        body: JSON.stringify(payload)
      });

      if (!response.ok) {
        const errorText = await response.text();
        console.error(`Failed to trigger workflow: ${response.status}`, errorText);
        return false;
      }

      console.log("✅ Catalog update workflow triggered successfully");
      return true;
    } catch (err) {
      console.error("Failed to trigger catalog update:", err);
      return false;
    }
  }
};  async saveCatalogToGitHub(data) {
    const content = JSON.stringify(data, null, 2);
    const message = `Update catalog: ${new Date().toLocaleString()}`;
    return await this.updateFile("public/catalog-data.json", content, message);
  }
};
